### ISSUE TITLE
module 'MinkowskiEngine' has no attribute '__version__

### ISSUE THREAD

**Issue by xje123456** [StefOe/DPCR-AGB#1]
module 'MinkowskiEngine' has no attribute '__version__
what problem is it?

**Comment by StefOe** [comment]
Hi, could you elaborate a little where you encounter this problem?

**Comment by xje123456** [comment]
An error occurred while installing the Minkowski Engine。
My configuration is as follows：
OS: Ubuntu 22.04
Cuda: 11.8
Gcc version: 7.5.0
Error reported as follows：
/root/MinkowskiEngine/src/spmm.cu: In instantiation of 'minkowski::coo_spmm(const at::Tensor&, const at::Tensor&, const at::Tensor&, int64_t, int64_t, const at::Tensor&, int64_t, bool)::<lambda()>::<lambda()> [with th_int_type = int]':
/root/MinkowskiEngine/src/spmm.cu:203:0: required from 'struct minkowski::coo_spmm(const at::Tensor&, const at::Tensor&, const at::Tensor&, int64_t, int64_t, const at::Tensor&, int64_t, bool)::<lambda()> [with th_int_type = int]::<lambda()>'
/root/MinkowskiEngine/src/spmm.cu:203:0: required from 'minkowski::coo_spmm(const at::Tensor&, const at::Tensor&, const at::Tensor&, int64_t, int64_t, const at::Tensor&, int64_t, bool)::<lambda()> [with th_int_type = int]'
/root/MinkowskiEngine/src/spmm.cu:203:0: required from 'struct minkowski::coo_spmm(const at::Tensor&, const at::Tensor&, const at::Tensor&, int64_t, int64_t, const at::Tensor&, int64_t, bool) [with th_int_type = int; int64_t = long int]::<lambda()>'
/root/MinkowskiEngine/src/spmm.cu:203:0: required from 'at::Tensor minkowski::coo_spmm(const at::Tensor&, const at::Tensor&, const at::Tensor&, int64_t, int64_t, const at::Tensor&, int64_t, bool) [with th_int_type = int; int64_t = long int]'
/root/MinkowskiEngine/src/spmm.cu:335:232: required from here
/root/MinkowskiEngine/src/spmm.cu:203:1428: internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1740
AT_DISPATCH_FLOATING_TYPES(vals.scalar_type(), "coo_spmm", [&] {
^
Please submit a full bug report,
with preprocessed source if appropriate.
See https://gcc.gnu.org/bugs/ for instructions.
error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1

**Comment by xje123456** [comment]
The code environment is a bit difficult to configure
In particular, the MinkowskiEngine package

**Comment by StefOe** [comment]
Did you try following the instructions in the README?
The point cloud packages, such as MinkowskiEngine are usually a bit of a hassle because there are no pre-compiled packages but with these instructions it worked on many machines for me and my colleagues. I just tried it again and it compiled alright, only the pip command changed slightly due to pip updates (for pip 23: pip install -U git+https://github.com/NVIDIA/MinkowskiEngine -v --no-deps --config-settings blas_include_dirs=${CONDA_PREFIX}/include --config-settings blas=openblas)

The error message does not seem helpful to me, one could try previous versions if this is something that happened in the last commits but it seems the code has not been changed for 3 years. Otherwise try a newer GCC (as some of their issues suggest, I use 8.5 or higher).

Sorry cannot help with this too much as I also just use that package and not maintain it myself.
Let me know if and how you solve this.

**Comment by xje123456** [comment]
OS: Ubuntu 18.04
cuda: 11.1
Pytorch:1.9
Gcc version: 7.5.0
I have successfully installed the MinkowskiEngine package on the above computer configuration, but I am not sure if it will affect others

**Comment by Fran-lose** [comment]
> 作系统： Ubuntu 18.04 cuda： 11.1 Pytorch：1.9 Gcc 版本： 7.5.0我已经在上述计算机配置上成功安装了 MinkowskiEngine 包，但我不确定它是否会影响其他人
Can you run this model with your own dataset? If so, could you share the format of the dataset? Thanks!
